### ISSUE TITLE
4.2.2不能安装

### ISSUE THREAD

**Issue by thisvip** [wizos/loread#1]
非常棒的项目，我一直在寻找一个电纸书上体验非常好的RSS客户端。本来想把你这个项目移植到电纸书上试试，但电纸书大部分都基于4.2.2版本。Android Studio也编译不通过。
无法体验，很遗憾。希望能支持4.2.2。然后一起把电纸书上的体验做到最佳，做Android电纸书的第一RSS客户端。:)
有意向可以加QQ 14671242 聊聊哦！

**Comment by wizos** [comment]
谢谢支持，不过我的技术和时间目前都还不能做到……
如果你想在 Kindle 上用 RSS ，我觉得 Reabble 会是一个更不错的选择。
