### ISSUE TITLE
什么时候更新？

### ISSUE THREAD

**Issue by caibye** [wizos/loread#2]

**Comment by wizos** [comment]
代码暂时不更新了，写的比较烂……
应用我已经上传到酷安：[https://www.coolapk.com/apk/168423](https://www.coolapk.com/apk/168423)

**Comment by geekjuruo** [comment]
你好，请问下载了整个项目，在我的android studio上运行项目，为什么老是在resolve dependencies of ：classpath的时候报错(Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom')？需要设置哪些才能在我的电脑上编译运行呢？谢谢
