### ISSUE TITLE
应该如何在我的电脑android studio for Mac上运行项目？

### ISSUE THREAD

**Issue by geekjuruo** [wizos/loread#3]
你好，请问下载了整个项目，在我的android studio上运行项目，为什么老是在resolve dependencies of ：classpath的时候报错(Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom')？需要设置哪些才能在我的电脑上编译运行呢？谢谢

**Comment by wizos** [comment]
你可以百度一下，类似的解决方法很多，大概率是因为你没有翻墙

**Comment by geekjuruo** [comment]
我可以确定我是可以翻墙的，并且还尝试了更改您的build.gradle中的值，但还是没有效果！不知道需要做什么设置

**Comment by wizos** [comment]
你本地安装了什么版本的gradle？改为这版本试试。

**Comment by geekjuruo** [comment]
gradle-4.4-all.zip,改了，却还是没有效果。

**Comment by wizos** [comment]
你开的是全局代理吗？
不行的话，根据描述的错误百度一下吧

**Comment by geekjuruo** [comment]
我的vpn是全局模式，尝试了修改gradle也还是不行，感觉我的AS很是玄学

**Comment by wizos** [comment]
我push了本地最新的版本，你再试试

**Comment by geekjuruo** [comment]
方便加个微信吗？我的微信号是lyh62125685

**Comment by geekjuruo** [comment]
<img width="1422" alt="2018-09-05 9 32 31" src="https://user-images.githubusercontent.com/26545506/45096505-469e9500-b153-11e8-8c39-8138d6ddf929.png">

**Comment by wizos** [comment]
这个图，也没看出错误了……
