### ISSUE TITLE
关于 Feedly Auth  的疑问

### ISSUE THREAD

**Issue by rantianhua** [wizos/loread#6]
根据 Feedly Auth 的 API 文档：https://developer.feedly.com/v3/auth/ 。在获取 Code 时，需要提供一个 redirect url 作为 webhook 以便 Feedly Cloud 返回 Code 。但是看代码实现通过 `startActivity` 打开其他能打开 URL 的 App 进行 Feedly 的用户登陆操作，然后在 `ProviderActivity` 的 `onNewIntent` 里面通过 Intent 获取到了 Response 。我比较好奇的是，那个 redirect url 从文档上理解的话应该是个 webhook ，Feedly Cloud 通过 HTTP 请求这个 URL 时把 Code 传过来，为什么这里可以直接从 Intent 里面拿到 Feedly Cloud 的 Response ？从 Feedly 的 API 文档中没有看到有这样的介绍，求指教。

**Comment by wizos** [comment]
从 ProviderActivity 的 getAccessToken 方法中，调用了抽象的 api.getAccessToken。
在其具体实现 FeedlyApi.getAccessToken 里，传入了 builder.add("redirect_uri", "palabre://feedlyauth");。
而且 AndroidManifest.xml 文件内对 ProviderActivity 定义了 palabre://feedlyauth，所以 Feedly Cloud 最后会调起 ProviderActivity.onNewIntent 方法

**Comment by rantianhua** [comment]
GET.
