### ISSUE TITLE
挺不错的 Android RSS App，提使用中遇到的的 Bug 和几个建议

### ISSUE THREAD

**Issue by cobaltdisco** [wizos/loread#7]
系统：Android 10
手机：Google Pixel 4 XL
订阅方式：Fever API

### Bug
1. 深色模式无法自动切换，即使在设置中选择了自动切换
2. 在实时开关深色模式时，点击订阅分类时，UI 颜色会出错

### 建议
1. 英语翻译有待优化：可以把翻译文件上传到 Crowdin 上，然后由其他自由译员来支持，不过我也可以来支持（常年英语环境，且翻译过某海外主流 App），看着翻译量挺少的。
2. 退出 App 时，会有个“Are you sure you want to exit the appUpdateModel?”提示，不过 Android 设计准则应该不则么提倡这种做法，后退时候就直接退出就行。
3. 查看订阅源的交互有点诡异，点击按钮后（底栏的第二个按钮），默认不是自动展开的（可能设计之初是为了让用户点击分类后再展开？），这块感觉交互得细想，似乎则么改都会有点诡异——但或许，用户其实不需要分类（可以看看打点，每个用户订阅数的百分位，了解每个用户的订阅数分布）。

但，真的是一个不错的安卓 RSS App。基本满足了 MVP 的需求：订阅、查看。

**Comment by wizos** [comment]
谢谢反馈 ！
1、目前的深色模式只是根据内置的时间判断来切换，而并没有实现系统推荐的模式切换。
2、部分 UI 会停留在切换之前的颜色这个问题，是引用的换肤库本身的 BUG，由于我对这块还不熟悉，暂时无法修复。未来看是不是切回官方推荐的换肤模式。
3、我之后试试看。如果您愿意帮助的话，本项目中就有待翻译的文件原文。
4、为了防止误操作会导致退出应用，所以增加了确认框。
5、这个设计一是我个人习惯分类的，订阅比较多。二是为了兼容“源被退订，但是该源下有星标文章的情况”，如果要知道是哪些文章，而不是去翻全部的星标文章，所以把所有未分类的订阅都默认分到了未分类当中。
6、你说的“订阅数百分位，了解订阅数分布”是指大家订阅的文章类型分布？没太懂意义。

**Comment by cobaltdisco** [comment]
3 好的，我来进行翻译吧，没啥问题。

6 验证功能影响的一个方式，比如如果发现 95% 的人订阅源都在 10 个左右，可能分类就没特别的意义了。不过 App 在开发本身的时候应该也是适应了开发者本身的喜好（“这个设计一是我个人习惯分类的，订阅比较多”），也不强求。

**Comment by wizos** [comment]
谢谢 ~
app 内的英文文案在 loread/app/src/main/res/values/strings.xml 文件中，中文文案在 loread/app/src/main/res/values-zh-rCN/strings.xml 内。
另外，第 6 个建议，我尝试了下，可以直接去掉“未分类”，已上架酷安。

**Comment by cobaltdisco** [comment]
好的，以及不知道目前 .xml 文件是否是最新的？对比了下，似乎和现在线上版本有点区别。

对于翻译，目前已经上传到 [Crowdin](https://crowdin.com/project/loread-rss)，正在翻译中。
